SELECT * FROM TAB;



SELECT PD_NAME AS PRODUCT_NAME , PD_COST AS PRICE FROM BANK_PRODUCT;

SELECT PD_NAME AS PRODUCT_NAME , PD_COST AS PRICE FROM BANK_PRODUCT ORDER BY PD_NAME ASC;
 
SELECT EMPLOYEE_NAME AS Name_ ,EMPLOYEE_PH AS Phone FROM CAR_MECHANIC;
SELECT EMP_NAME AS Name_ ,EMP_ADDRESS AS Address_ FROM RES_STAFF ORDER BY EMP_ADDRESS DESC;

SELECT DISTINCT PATIENT_ID AS Name_ FROM HOS_PATIENT;

SELECT CUS_NAME AS Name_ ,CUS_ADDRESS AS Address_ FROM RES_CUSTOMER WHERE CUS_ADDRESS <> 'Bhubaneshwar' ;

SELECT CUS_NAME AS Name_ ,CUS_ADDRESS AS Address_ FROM RES_CUSTOMER WHERE CUS_ADDRESS = 'Lucknow' ;


CREATE TABLE TESTING 
(ID NUMBER(4) NOT NULL,
NAME_ VARCHAR2(10) DEFAULT 'NO NAME');


