--


SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME, s.NAME AS SCHOOL_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID;


SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME, j.TITLE, j.SALARY
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID;


SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME, j.NAME, j.TITLE, (j.SALARY + j.BONUS) AS TOTAL_SALARY
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
WHERE j.BONUS IS NOT NULL;

SELECT DISTINCT s.FIRST_NAME || ' ' || s.LAST_NAME AS SUPERVISOR_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE s ON e.SUPERVISOR_ID = s.ID;

SELECT s.ID, s.FIRST_NAME || ' ' || s.LAST_NAME AS SUPERVISOR_NAME, COUNT(e.ID) AS TOTAL_SUPERVISEES
FROM lab6_EMPLOYEE s
JOIN lab6_EMPLOYEE e ON s.ID = e.SUPERVISOR_ID
GROUP BY s.ID, s.FIRST_NAME, s.LAST_NAME;



SELECT sc.NAME AS SCHOOL, s.ID, s.FIRST_NAME || ' ' || s.LAST_NAME AS SUPERVISOR, COUNT(e.ID) AS SUPERVISEES
FROM lab6_EMPLOYEE s
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON s.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL sc ON ea.SCHOOL_ID = sc.ID
JOIN lab6_EMPLOYEE e ON s.ID = e.SUPERVISOR_ID
GROUP BY sc.NAME, s.ID, s.FIRST_NAME, s.LAST_NAME;



SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE j.TITLE = 'Associate Professor' AND s.NAME IN ('Computer Engineering', 'Electronic Engineering');


SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE j.TITLE = 'Professor' AND s.NAME IN ('Computer Engineering', 'Mechanical Engineering') AND j.BONUS IS NULL;


SELECT s.NAME, j.TITLE, AVG(j.SALARY) AS AVG_SALARY, COUNT(e.ID) AS EMP_COUNT
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
GROUP BY s.NAME, j.TITLE;


SELECT e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
WHERE ea.SCHOOL_ID IN (
    SELECT ea2.SCHOOL_ID 
    FROM lab6_EMPLOYEE e2 
    JOIN lab6_EMPLOYEE_ALIGNMENT ea2 ON e2.ID = ea2.EMPLOYEE_ID 
    WHERE e2.FIRST_NAME = 'John' AND e2.LAST_NAME = 'Smith'
) AND (e.FIRST_NAME != 'John' OR e.LAST_NAME != 'Smith');


--11


SELECT j.TITLE, COUNT(e.ID) AS EMP_COUNT
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE (j.SALARY + NVL(j.BONUS, 0)) > 100000 AND s.NAME != 'Computer Engineering'
GROUP BY j.TITLE;



SELECT COUNT(*) AS MultipleSchool FROM (
    SELECT EMPLOYEE_ID 
    FROM lab6_EMPLOYEE_ALIGNMENT 
    GROUP BY EMPLOYEE_ID 
    HAVING COUNT(SCHOOL_ID) > 1);



SELECT s.NAME, COUNT(e.ID) AS HIRED_LAST_YEAR
FROM lab6_SCHOOL s
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON s.ID = ea.SCHOOL_ID
JOIN lab6_EMPLOYEE e ON ea.EMPLOYEE_ID = e.ID
WHERE e.HIRE_DATE >= DATE'2025-01-01' AND e.HIRE_DATE <= DATE'2025-12-31'
GROUP BY s.NAME;


SELECT s.NAME, COUNT(e.ID) AS PROF_HIRED_LAST_MONTH
FROM lab6_SCHOOL s
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON s.ID = ea.SCHOOL_ID
JOIN lab6_EMPLOYEE e ON ea.EMPLOYEE_ID = e.ID
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
WHERE j.TITLE = 'Professor' 
AND e.HIRE_DATE >= DATE'2026-01-01' AND e.HIRE_DATE <= DATE'2026-01-31'
GROUP BY s.NAME;



SELECT s.NAME, e.FIRST_NAME || ' ' || e.LAST_NAME AS FULL_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE j.TITLE IN ('Professor', 'Associate Professor') 
AND EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM e.HIRE_DATE)>=4 ;


CREATE TABLE LAB6_PROF_COMP_ENG AS
SELECT e.ID, e.LAST_NAME, e.FIRST_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_PAY ep ON e.ID = ep.EMPLOYEE_ID
JOIN lab6_JOB j ON ep.JOB_ID = j.ID
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE j.TITLE = 'Professor' AND s.NAME = 'Computer Engineering';



SELECT e.FIRST_NAME, e.LAST_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE s.NAME = 'Computer Engineering'
UNION
SELECT e.FIRST_NAME, e.LAST_NAME
FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE s.NAME = 'Civil Engineering';




CREATE TABLE EMP_24012017 AS
    SELECT * FROM lab6_EMPLOYEE;



INSERT INTO EMP_24012017
SELECT e.* FROM lab6_EMPLOYEE e
JOIN lab6_EMPLOYEE_ALIGNMENT ea ON e.ID = ea.EMPLOYEE_ID
JOIN lab6_SCHOOL s ON ea.SCHOOL_ID = s.ID
WHERE s.NAME = 'Computer Engineering';




CREATE SEQUENCE dummy_seq START WITH 1 INCREMENT BY 1;



CREATE TABLE lab6_seq_table (
    ID INT ,
    NAME VARCHAR(50)
);

INSERT INTO lab6_seq_table VALUES (dummy_seq.NEXTVAL, 'Arka');
INSERT INTO lab6_seq_table VALUES (dummy_seq.NEXTVAL, 'Arnav');
SELECT * from LAB6_SEQ_TABLE;
commit;


--spool '/home/avo/test2_2405036.sql';
--spool off;






/*CREATE SEQUENCE tablename_colname_seq;

CREATE TABLE tablename (
    colname integer NOT NULL DEFAULT nextval('tablename_colname_seq')
);

ALTER SEQUENCE tablename_colname_seq OWNED BY tablename.colname;
*/
