SET ECHO ON;
SET FEEDBACK ON;
SET SERVEROUTPUT ON;
SET PAGESIZE 100;
SET LINESIZE 200;

spool '/home/avo/test_spool.sql';


SELECT NAME FROM lab6_SCHOOL WHERE ID IN (
    SELECT SCHOOL_ID 
    FROM lab6_EMPLOYEE_ALIGNMENT 
    WHERE EMPLOYEE_ID IN (
        SELECT ID FROM lab6_EMPLOYEE 
        WHERE FIRST_NAME = 'Andrew' AND LAST_NAME = 'Brown'
    )
);

SELECT FIRST_NAME || ' ' || LAST_NAME AS SUPERVISOR_NAME 
FROM lab6_EMPLOYEE 
WHERE ID = (
    SELECT SUPERVISOR_ID 
    FROM lab6_EMPLOYEE 
    WHERE ID = 128433
);

SELECT FIRST_NAME, LAST_NAME 
FROM lab6_EMPLOYEE 
WHERE ID IN (
    SELECT EMPLOYEE_ID 
    FROM lab6_EMPLOYEE_ALIGNMENT 
    WHERE SCHOOL_ID IN (
        SELECT SCHOOL_ID 
        FROM lab6_EMPLOYEE_ALIGNMENT 
        WHERE EMPLOYEE_ID IN (
            SELECT ID 
            FROM lab6_EMPLOYEE 
            WHERE FIRST_NAME = 'Rod' AND LAST_NAME = 'Marsh'
        )
    )
);

SELECT FIRST_NAME, LAST_NAME 
FROM lab6_EMPLOYEE 
WHERE ID IN (
    SELECT EMPLOYEE_ID 
    FROM lab6_EMPLOYEE_PAY 
    WHERE JOB_ID IN (
        SELECT ID FROM lab6_JOB WHERE TITLE = (
            SELECT J.TITLE 
            FROM lab6_JOB J 
            JOIN lab6_EMPLOYEE_PAY EP ON J.ID = EP.JOB_ID 
            JOIN lab6_EMPLOYEE E ON EP.EMPLOYEE_ID = E.ID 
            WHERE E.FIRST_NAME = 'Stanely' AND E.LAST_NAME = 'Garner'
        )
    )
);


SELECT FIRST_NAME, LAST_NAME 
FROM lab6_EMPLOYEE 
WHERE HIRE_DATE < (
    SELECT HIRE_DATE 
    FROM lab6_EMPLOYEE 
    WHERE FIRST_NAME = 'Larry' AND LAST_NAME = 'Houston'
);


SELECT COUNT(*) 
FROM lab6_EMPLOYEE_ALIGNMENT 
WHERE SCHOOL_ID = (
    SELECT ID 
    FROM lab6_SCHOOL 
    WHERE NAME = 'School of Computer Engineering'
);


SELECT COUNT(*) FROM lab6_EMPLOYEE_ALIGNMENT 
WHERE SCHOOL_ID = (SELECT ID FROM lab6_SCHOOL WHERE NAME = 'School of Civil Engineering')
AND EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM lab6_EMPLOYEE_PAY 
                    WHERE JOB_ID IN (SELECT ID FROM lab6_JOB WHERE TITLE = 'Professor'));


SELECT E.FIRST_NAME, E.LAST_NAME FROM lab6_EMPLOYEE E, lab6_EMPLOYEE_PAY EP, lab6_JOB J, lab6_EMPLOYEE_ALIGNMENT EA 
WHERE E.ID = EP.EMPLOYEE_ID AND EP.JOB_ID = J.ID AND E.ID = EA.EMPLOYEE_ID 
AND J.TITLE = 'Associate Professor' 
AND J.SALARY = (SELECT MIN(J2.SALARY) FROM lab6_EMPLOYEE_PAY EP2, lab6_JOB J2, lab6_EMPLOYEE_ALIGNMENT EA2 
                WHERE EP2.JOB_ID = J2.ID AND EP2.EMPLOYEE_ID = EA2.EMPLOYEE_ID 
                AND EA2.SCHOOL_ID = EA.SCHOOL_ID AND J2.TITLE = 'Associate Professor');



SELECT E.FIRST_NAME, E.LAST_NAME FROM lab6_EMPLOYEE E, lab6_EMPLOYEE_PAY EP, lab6_JOB J, lab6_EMPLOYEE_ALIGNMENT EA 
WHERE E.ID = EP.EMPLOYEE_ID AND EP.JOB_ID = J.ID AND E.ID = EA.EMPLOYEE_ID 
AND J.TITLE = 'Professor' 
AND J.SALARY = (SELECT MAX(J2.SALARY) FROM lab6_EMPLOYEE_PAY EP2, lab6_JOB J2, lab6_EMPLOYEE_ALIGNMENT EA2 
                WHERE EP2.JOB_ID = J2.ID AND EP2.EMPLOYEE_ID = EA2.EMPLOYEE_ID 
                AND EA2.SCHOOL_ID = EA.SCHOOL_ID AND J2.TITLE = 'Professor');



SELECT S.NAME, AVG(J.SALARY) FROM lab6_SCHOOL S, lab6_EMPLOYEE_ALIGNMENT EA, lab6_EMPLOYEE_PAY EP, lab6_JOB J 
WHERE S.ID = EA.SCHOOL_ID AND EA.EMPLOYEE_ID = EP.EMPLOYEE_ID AND EP.JOB_ID = J.ID 
GROUP BY S.NAME;



SELECT S.NAME, COUNT(EA.EMPLOYEE_ID)
FROM lab6_SCHOOL S, lab6_EMPLOYEE_ALIGNMENT EA
WHERE S.ID = EA.SCHOOL_ID
AND EA.EMPLOYEE_ID IN (SELECT EP.EMPLOYEE_ID FROM lab6_EMPLOYEE_PAY EP, lab6_JOB J 
                       WHERE EP.JOB_ID = J.ID AND J.TITLE = 'Assistant Professor'
                       AND J.SALARY > (SELECT AVG(J2.SALARY) 
                                       FROM lab6_JOB J2, lab6_EMPLOYEE_PAY EP2, lab6_EMPLOYEE_ALIGNMENT EA2
                                       WHERE J2.ID = EP2.JOB_ID AND EP2.EMPLOYEE_ID = EA2.EMPLOYEE_ID
                                       AND EA2.SCHOOL_ID = S.ID
                                       AND J2.TITLE = 'Assistant Professor'))
GROUP BY S.NAME;


SELECT FIRST_NAME, LAST_NAME, PHONE, PAGER 
FROM lab6_EMPLOYEE 
WHERE ID = (SELECT SUPERVISOR_ID FROM lab6_EMPLOYEE 
            WHERE FIRST_NAME = 'Jose' AND LAST_NAME = 'Diaz');


SELECT FIRST_NAME, LAST_NAME FROM lab6_EMPLOYEE 
WHERE ID NOT IN (SELECT EMPLOYEE_ID FROM lab6_EMPLOYEE_ALIGNMENT);


SELECT FIRST_NAME, LAST_NAME FROM lab6_EMPLOYEE 
WHERE ID IN (SELECT EMPLOYEE_ID FROM lab6_EMPLOYEE_ALIGNMENT 
             GROUP BY EMPLOYEE_ID HAVING COUNT(SCHOOL_ID) > 1);

SELECT FIRST_NAME, LAST_NAME FROM lab6_EMPLOYEE 
WHERE (SYSDATE - HIRE_DATE) / 365 > 5
AND ID IN (SELECT EMPLOYEE_ID FROM lab6_EMPLOYEE_ALIGNMENT 
           WHERE SCHOOL_ID IN (SELECT ID FROM lab6_SCHOOL 
                               WHERE NAME IN ('School of Computer Science', 'School of Mechanical Engineering')));


SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM lab6_EMPLOYEE 
WHERE ID IN (SELECT EMPLOYEE_ID FROM lab6_EMPLOYEE_ALIGNMENT 
             WHERE SCHOOL_ID IN (SELECT ID FROM lab6_SCHOOL 
                                 WHERE NAME IN ('School of Computer Science', 'School of Electrical Engineering')))
AND ID IN (SELECT EMPLOYEE_ID FROM lab6_EMPLOYEE_PAY 
           WHERE JOB_ID IN (SELECT ID FROM lab6_JOB WHERE TITLE = 'Assistant Professor'))
ORDER BY HIRE_DATE DESC;

spool off;




