-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-25 07:51:52 IST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Accident 
    ( 
     REPORT_ID NUMBER  NOT NULL , 
     "DATE"    DATE  NOT NULL , 
     Location  VARCHAR2 (150) , 
     Car_VIN   NUMBER  NOT NULL , 
     Car_ID    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Accident 
    ADD CONSTRAINT Accident_PK PRIMARY KEY ( REPORT_ID, Car_VIN, Car_ID ) ;

CREATE TABLE Car 
    ( 
     VIN         NUMBER  NOT NULL , 
     MODEL_NAME  VARCHAR2 (50) , 
     YEAR        DATE , 
     Customer_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Car 
    ADD CONSTRAINT Car_PK PRIMARY KEY ( VIN, Customer_ID ) ;

CREATE TABLE Customer 
    ( 
     ID   NUMBER  NOT NULL , 
     NAME VARCHAR2 (50) 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( ID ) ;

ALTER TABLE Accident 
    ADD CONSTRAINT Accident_Car_FK FOREIGN KEY 
    ( 
     Car_VIN,
     Car_ID
    ) 
    REFERENCES Car 
    ( 
     VIN,
     Customer_ID
    ) 
;

ALTER TABLE Car 
    ADD CONSTRAINT Car_Customer_FK FOREIGN KEY 
    ( 
     Customer_ID
    ) 
    REFERENCES Customer 
    ( 
     ID
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
