-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-25 08:07:46 IST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE DOCTORS 
    ( 
     ID         NUMBER  NOT NULL , 
     NAME       VARCHAR2 (50)  NOT NULL , 
     SPECIALITY VARCHAR2 (50) 
    ) 
;

ALTER TABLE DOCTORS 
    ADD CONSTRAINT DOCTORS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PATIENT 
    ( 
     ID   NUMBER  NOT NULL , 
     NAME VARCHAR2 (50)  NOT NULL , 
     DOB  DATE 
    ) 
;

ALTER TABLE PATIENT 
    ADD CONSTRAINT PATIENT_PK PRIMARY KEY ( ID ) ;

CREATE TABLE TESTS 
    ( 
     TEST_ID    NUMBER  NOT NULL , 
     NAME       VARCHAR2 (50) , 
     "DATE"     DATE , 
     RESULT     VARCHAR2 (50) , 
     PATIENT_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE TESTS 
    ADD CONSTRAINT TESTS_PK PRIMARY KEY ( TEST_ID, PATIENT_ID ) ;

CREATE TABLE Treats 
    ( 
     DOCTORS_ID NUMBER  NOT NULL , 
     PATIENT_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Treats 
    ADD CONSTRAINT Treats_PK PRIMARY KEY ( DOCTORS_ID, PATIENT_ID ) ;

ALTER TABLE TESTS 
    ADD CONSTRAINT TESTS_PATIENT_FK FOREIGN KEY 
    ( 
     PATIENT_ID
    ) 
    REFERENCES PATIENT 
    ( 
     ID
    ) 
;

ALTER TABLE Treats 
    ADD CONSTRAINT Treats_DOCTORS_FK FOREIGN KEY 
    ( 
     DOCTORS_ID
    ) 
    REFERENCES DOCTORS 
    ( 
     ID
    ) 
;

ALTER TABLE Treats 
    ADD CONSTRAINT Treats_PATIENT_FK FOREIGN KEY 
    ( 
     PATIENT_ID
    ) 
    REFERENCES PATIENT 
    ( 
     ID
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
