SELECT * FROM ALL_TABLES;
SELECT SYSDATE FROM DUAL;
SELECT 'HelloWorld' FROM DUAL;
SELECT SYSTIMESTAMP ,' HELLO WORLD' ,5*5 FROM DUAL;
SELECT 'TRUE' FROM DUAL WHERE 'Caps' = 'Caps';
SELECT 'TRUE' FROM DUAL WHERE 'Caps' = 'caps';