SET ECHO ON;
SET FEEDBACK ON;
SET SERVEROUTPUT ON;
SET PAGESIZE 100;
SET LINESIZE 200;

spool '/home/avo/lab8_spool_2405036.sql';


CREATE VIEW VIEW_EMP_SCHOOL AS 
SELECT E.ID, E.LAST_NAME, E.FIRST_NAME, E.MIDDLE_NAME, E.SEX, E.HIRE_DATE, S.ID AS SCHOOL_ID, S.NAME AS SCHOOL_NAME
FROM LAB6_EMPLOYEE E
JOIN LAB6_EMPLOYEE_ALIGNMENT EA ON E.ID = EA.EMPLOYEE_ID
JOIN LAB6_SCHOOL S ON EA.SCHOOL_ID = S.ID;

CREATE VIEW VIEW_EMP_JOB AS 
SELECT E.ID, E.LAST_NAME, E.FIRST_NAME, J.ID AS JOB_ID, J.NAME AS JOB_NAME, J.TITLE
FROM LAB6_EMPLOYEE E
JOIN LAB6_EMPLOYEE_PAY EP ON E.ID = EP.EMPLOYEE_ID
JOIN LAB6_JOB J ON EP.JOB_ID = J.ID;

CREATE VIEW VIEW_EMP_PAY AS 
SELECT E.ID, E.FIRST_NAME, E.LAST_NAME, J.SALARY, J.BONUS
FROM LAB6_EMPLOYEE E
JOIN LAB6_EMPLOYEE_PAY EP ON E.ID = EP.EMPLOYEE_ID
JOIN LAB6_JOB J ON EP.JOB_ID = J.ID;

CREATE VIEW VIEW_SCHOOL_STATS AS 
SELECT S.NAME AS SCHOOL_NAME, COUNT(EA.EMPLOYEE_ID) AS NUM_EMPLOYEES, AVG(J.SALARY) AS AVG_SALARY
FROM LAB6_SCHOOL S
JOIN LAB6_EMPLOYEE_ALIGNMENT EA ON S.ID = EA.SCHOOL_ID
JOIN LAB6_EMPLOYEE_PAY EP ON EA.EMPLOYEE_ID = EP.EMPLOYEE_ID
JOIN LAB6_JOB J ON EP.JOB_ID = J.ID
GROUP BY S.NAME;

--CREATE USER TEST_USER IDENTIFIED BY 123;

GRANT SELECT ON LAB6_EMPLOYEE TO TEST_USER;

GRANT UPDATE ON LAB6_SCHOOL TO TEST_USER;

GRANT DELETE ON LAB6_JOB TO TEST_USER;

CREATE SYNONYM SYN_EMP_SCHOOL FOR VIEW_EMP_SCHOOL;

--DROP SYNONYM SYN_EMP_SCHOOL;




-- Step 1: Create the view joining Employee, School, and Job
CREATE VIEW v_emp_school_job AS 
SELECT E.*, S.NAME AS SCHOOL_NAME, J.TITLE, J.SALARY, J.BONUS
FROM lab6_EMPLOYEE E 
JOIN lab6_EMPLOYEE_ALIGNMENT EA ON E.ID = EA.EMPLOYEE_ID 
JOIN lab6_SCHOOL S ON EA.SCHOOL_ID = S.ID
JOIN lab6_EMPLOYEE_PAY EP ON E.ID = EP.EMPLOYEE_ID
JOIN lab6_JOB J ON EP.JOB_ID = J.ID;

-- Step 2: Create the synonym
CREATE SYNONYM syn_emp_school_job FOR v_emp_school_job;





-- Step 1: Create the comprehensive view
CREATE VIEW v_full_employee_details AS 
SELECT E.*, S.NAME AS SCHOOL_NAME, J.TITLE, J.SALARY, J.BONUS, EP.JOB_ID
FROM lab6_EMPLOYEE E 
JOIN lab6_EMPLOYEE_ALIGNMENT EA ON E.ID = EA.EMPLOYEE_ID 
JOIN lab6_SCHOOL S ON EA.SCHOOL_ID = S.ID
JOIN lab6_EMPLOYEE_PAY EP ON E.ID = EP.EMPLOYEE_ID
JOIN lab6_JOB J ON EP.JOB_ID = J.ID;

-- Step 2: Create the synonym
CREATE SYNONYM syn_full_details FOR v_full_employee_details;






CREATE INDEX idx_emp_sex ON lab6_EMPLOYEE(SEX);

CREATE INDEX idx_emp_full_name ON lab6_EMPLOYEE(FIRST_NAME, MIDDLE_NAME, LAST_NAME);

SAVEPOINT lab7_savepoint;

ALTER INDEX idx_emp_full_name RENAME TO idx_emp_names_new;

DROP INDEX idx_emp_names_new;

RENAME VIEW_EMP_PAY TO VIEW_EMP_PAY_rename;

DROP VIEW VIEW_EMP_PAY_rename;

COMMIT;

DROP VIEW VIEW_EMP_SCHOOL;

ROLLBACK;




SPOOL OFF;


